project:
  type: website
  output-dir: _site

website:
  title: "Assignment 2"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: Questions

format:
  html:
    theme: quarts
    mainfoint: arial
    fontcolor: "#938d93"
    linkcolor: "#992597"
    css: styles.css
    toc: true



